server:
  port: ${APP_PORT}
spring:
  application:
    name: user
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true