CREATE TABLE RECIPE (
  ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  SERVINGS INT,
  NAME VARCHAR(255) NOT NULL,
  INGREDIENTS VARCHAR(255) NOT NULL,
  INSTRUCTIONS VARCHAR(255) NOT NULL,
  VEGETARIAN BOOLEAN,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  PRIMARY KEY (ID)
);